// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock, ReferencePage } from "emdash";

export interface Conversation {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  context: string;
  edited_summary: string;
  lesson: string;
  reviewed_at: string;
  source_reviewed: boolean;
  public_safe: boolean;
  proof_boundary: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface DispatchContentProseV1Block {
  _type: "prose";
  _version: 1;
  _key: string;
  "content": PortableTextBlock[];
}

export type DispatchContentProseBlock = DispatchContentProseV1Block;

export interface DispatchContentPullQuoteV1Block {
  _type: "pull_quote";
  _version: 1;
  _key: string;
  "quote": string;
  "attribution"?: string | null;
}

export type DispatchContentPullQuoteBlock = DispatchContentPullQuoteV1Block;

export interface DispatchContentCalloutV1Block {
  _type: "callout";
  _version: 1;
  _key: string;
  "title": string;
  "body": string;
  "kind": "plain" | "evidence" | "boundary";
}

export type DispatchContentCalloutBlock = DispatchContentCalloutV1Block;

export interface DispatchContentTechnicalPlateV1Block {
  _type: "technical_plate";
  _version: 1;
  _key: string;
  "id": string;
  "number": string;
  "title": string;
  "variant": "flow" | "loop" | "ladder";
  "note"?: string | null;
  "steps"?: { "label": string; "title": string; "detail"?: string | null }[] | null;
}

export type DispatchContentTechnicalPlateBlock = DispatchContentTechnicalPlateV1Block;

export interface DispatchContentDiagramPlateV1Block {
  _type: "diagram_plate";
  _version: 1;
  _key: string;
  "diagram_id": "lineage" | "pirates-parity";
  "title": string;
  "description": string;
  "caption": string;
  "transcript": PortableTextBlock[];
}

export type DispatchContentDiagramPlateBlock = DispatchContentDiagramPlateV1Block;

export interface DispatchContentImagePlateV1Block {
  _type: "image_plate";
  _version: 1;
  _key: string;
  "image": { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  "caption"?: string | null;
  "variant"?: "wide" | "full-bleed" | "inline" | null;
}

export type DispatchContentImagePlateBlock = DispatchContentImagePlateV1Block;

export interface DispatchContentEvidenceLinkV1Block {
  _type: "evidence_link";
  _version: 1;
  _key: string;
  "evidence_key": string;
  "label": string;
  "context"?: string | null;
}

export type DispatchContentEvidenceLinkBlock = DispatchContentEvidenceLinkV1Block;

export interface DispatchContentProjectReferenceV1Block {
  _type: "project_reference";
  _version: 1;
  _key: string;
  "project_key": string;
  "label"?: string | null;
}

export type DispatchContentProjectReferenceBlock = DispatchContentProjectReferenceV1Block;

export interface DispatchContentCapabilityReviewV1Block {
  _type: "capability_review";
  _version: 1;
  _key: string;
  "capability_key": string;
  "provider_key": string;
  "title": string;
  "ownership": string;
  "reviewed_at": string;
  "package_name": string;
  "available_version": string;
  "contract_version": string;
  "package_url": string;
  "package_sha256": string;
  "programme_url": string;
  "documentation_url": string;
  "stations_url": string;
  "profiles_url": string;
  "evidence_key": string;
  "boundary": string;
  "consumers": { "project_key": string; "issue_url": string; "station_id": string; "scope": string; "planned": boolean; "in_progress": boolean; "implemented": boolean; "deployed": boolean; "verified": boolean; "installed_version"?: string | null; "deployed_revision"?: string | null; "release_evidence_key"?: string | null; "interaction_evidence_key"?: string | null; "evidence_key": string }[];
}

export type DispatchContentCapabilityReviewBlock = DispatchContentCapabilityReviewV1Block;

export type DispatchContentBlock = DispatchContentProseBlock | DispatchContentPullQuoteBlock | DispatchContentCalloutBlock | DispatchContentTechnicalPlateBlock | DispatchContentDiagramPlateBlock | DispatchContentImagePlateBlock | DispatchContentEvidenceLinkBlock | DispatchContentProjectReferenceBlock | DispatchContentCapabilityReviewBlock;

export interface Dispatch {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  kind: "Field note" | "Factory incident" | "Founding essay" | "Case study" | "Conversation" | "Doctrine" | "Portfolio report";
  deck: string;
  review_date: string;
  source_reference: string;
  lead: string;
  lesson: string;
  public_safe: boolean;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: DispatchContentBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface EvidenceRecord {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  project_key: string;
  snapshot_key?: string;
  claim: string;
  evidence_kind: "observation" | "source evidence" | "implementation" | "merge/integration" | "qualification" | "production verification" | "owner acceptance" | "physical proof";
  evidence_state: "reviewed" | "reported" | "not established";
  occurred_at?: string;
  reviewed_at: string;
  summary: string;
  source_label?: string;
  source_url?: string;
  revision?: string;
  public_safe: boolean;
  proof_boundary: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface FactorySnapshot {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  reviewed_at: string;
  source_description: string;
  scope: string;
  editorial_notes?: string;
  public_safe: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Incident {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  project_key: string;
  snapshot_key: string;
  dispatch_slug: string;
  initial_belief: string;
  what_happened: string;
  evidence: string;
  root_cause: string;
  factory_change: string;
  later_reuse?: string;
  reviewed_at: string;
  public_safe: boolean;
  proof_boundary: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ProjectStatuse {
  id: string;
  slug: string | null;
  status: string;
  project_key: string;
  snapshot_key: string;
  state: string;
  state_tone: "green" | "amber" | "red" | "quiet";
  current: string;
  next_proof: string;
  proof_boundary: string;
  reviewed_at: string;
  sort_order: number;
  public_safe: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  index: string;
  discipline: string;
  title: string;
  summary: string;
  why: string;
  teaches: string;
  site_url?: string;
  site_og_image?: string;
  site_og_title?: string;
  site_og_description?: string;
  site_favicon?: string;
  preview_alt?: string;
  preview_caption?: string;
  public_safe: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ConversationReferences {
  project: ReferencePage<Project>;
}

export interface DispatchReferences {
  projects: ReferencePage<Project>;
}

export interface EvidenceRecordReferences {
  project: ReferencePage<Project>;
  snapshot: ReferencePage<FactorySnapshot>;
}

export interface IncidentReferences {
  project: ReferencePage<Project>;
  snapshot: ReferencePage<FactorySnapshot>;
  dispatch: ReferencePage<Dispatch>;
}

export interface ProjectStatuseReferences {
  project: ReferencePage<Project>;
  snapshot: ReferencePage<FactorySnapshot>;
}

declare module "emdash" {
  interface EmDashCollections {
    conversations: Conversation;
    dispatches: Dispatch;
    evidence_records: EvidenceRecord;
    factory_snapshots: FactorySnapshot;
    incidents: Incident;
    project_statuses: ProjectStatuse;
    projects: Project;
  }
  interface EmDashCollectionReferences {
    conversations: ConversationReferences;
    dispatches: DispatchReferences;
    evidence_records: EvidenceRecordReferences;
    incidents: IncidentReferences;
    project_statuses: ProjectStatuseReferences;
  }
}